### ISSUE TITLE
Boards out of sync after castling

### ISSUE THREAD

**Issue by gulllberg** [Lupusa87/BlazorChess#1]
![Screenshot 2019-05-09 at 09 46 15](https://user-images.githubusercontent.com/22147839/57445877-963ddf00-7253-11e9-8082-2bb5f9462f87.png)

After castling only the king moved on the second board, the rook stayed in corner. See attached screenshot.

**Comment by Lupusa87** [comment]
thank you, this is not complete engine, it is for demontration purposes only.
